
name: Animal Farm NodeJS CI
on:
  push:
    branches:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    environment: demo
    outputs:
      matrix: ${{ steps.demo.outputs.sample }}
    steps:
    - name: Run tests
      run: echo "sample"
    - name: demo
      run: echo "sample=${{ vars.TEST_OS_VERSION }}" >> $GITHUB_OUTPUT

  example_matrix:
    runs-on: ubuntu-latest
    needs: build
    environment: demo
    strategy:
      matrix:
        version: ${{ needs.build.outputs.matrix }}
    steps:
    - name: devil
      run: echo "sample"