
name: Animal Farm NodeJS CI
on:
  push:
    branches:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    environment: demo
    steps:
    - name: Run tests
      run: echo "sample"
    - name: demo
      run: echo ${{ vars.TEST_OS_VERSION }}

  # build2:
  #   runs-on: ubuntu-latest
  #   environment: demo
  #   strategy:
  #     matrix:
  #       python-version: ${{ vars.TEST_OS_VERSION }}
  #   steps:
  #   - name: Run tests
  #     run: echo "sample"
  #   - name: demo
  #     run: echo 