
name: Animal Farm NodeJS CI
on:
  push:
    branches:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    environment: demo
    outputs:
      matrix: ${{ steps.demo.outputs.sample }}
    steps:
    - name: Run tests
      run: echo "${{ vars.DEMO }}"
    - name: demo
      id: demo
      run: echo "sample=${{ vars.DEMO }}" >> $GITHUB_OUTPUT

  example_matrix:
    runs-on: ubuntu-latest
    needs: build
    environment: demo
    strategy:
      matrix:
        version: ${{fromJson(needs.job1.outputs.matrix)}}
    steps:
    - name: devil
      run: echo "sample"